name: 'Build CLI and attach binary to GitHub release'

on:
  release:
    types: [published]

jobs:
  build:
    name: 'Build CLI and attach binary to GitHub release'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: 'Checkout'
        uses: actions/checkout@v2

      # Setup Go
      - name: 'Setup Go'
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - run: go version

      # Build CLI binaries
      - name: 'Build CLI'
        run: |
          set -e -x
          sudo apt-get update && sudo apt-get install -y -u wget
          export VARIANT_VERSION=0.37.0
          wget -q https://github.com/mumoshu/variant2/releases/download/v${VARIANT_VERSION}/variant_${VARIANT_VERSION}_linux_amd64.tar.gz && \
           tar -zvxf variant*.tar.gz variant && \
           sudo mv variant /usr/local/bin/variant2 && \
           rm -f variant*.tar.gz
          export CGO_ENABLED=1
          variant2 export binary $PWD $PWD/atmos/atmos
          $PWD/atmos/atmos help

      # Attach Go binaries to GitHub Release
      - name: 'Attach CLI binary to GitHub release'
        uses: cloudposse/actions/github/release-assets@0.23.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_PATH: $PWD/atmos
