name: 'Build CLI and attach binary to GitHub release'

on:
  release:
    types: [published]

jobs:
  build:
    name: 'Build CLI and attach binary to GitHub release'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: 'Checkout'
        uses: actions/checkout@v2

      # Setup Go
      - name: 'Setup Go'
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - run: go version

      # Build CLI binaries
      - name: 'Build CLI'
        run: |
          set -e -x
          sudo apt update
          sudo apt install cloudposse
          sudo apt-get update && sudo apt-get install -y -u variant2
          export CGO_ENABLED=1
          variant2 export binary ${{ github.workspace }}/release/${{ github.event.repository.name }}_ atmos
          ./atmos help

      # Attach Go binaries to GitHub Release
      - name: 'Attach CLI binary to GitHub release'
        uses: cloudposse/actions/github/release-assets@0.23.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_PATH: ${{ github.workspace }}/release/${{ github.event.repository.name }}_*
